export const SELECTPATH="SELECTPATH";
export const ADDITEM="ADDITEM";
export const SAVEITEM="SAVEITEM";
export const CANCELITEM="CANCELITEM";
export const DELETEITEM="DELETEITEM";
export const RENAMEITEM="RENAMEITEM";
export const SEARCHITEMS="SEARCHITEMS";